### PR TITLE
Make library compatible with both Python 2 and Python 3 (future module)

### PR DESCRIPTION
**Pull request by codingsparse**
ref: http://python-future.org/compatible_idioms.html

### CODE REVIEW

**Comment by Refefer** [comment]
Missed this - will check it out tonight.

**Comment by Refefer** [comment]
Library changes looks good.  Would you be up for updating bin/fxml.py as well?

**Comment by codingsparse** [comment]
Yes just made the bin/fxml.py compatible with python 3 as well :)

**Comment by Refefer** [comment]
:+1:

**Pull request merged**
